package main.java.trees;

public enum TreeNodeType {

	// STRUCTURAL
	PROGRAM, PROCEDURE, PROCEDURE_ID, PROCEDURE_BLOCK, STATEMENT_BLOCK,
	
	// NON-TERMINALS
	CONDITIONAL_STATEMENT, LOOP, REFERENCE, REFERENCE_VALUE, COMPOUND_STATEMENT, CONDITION, CONDITION_BODY, STATEMENT,
	
	// TERMINALS
	KEYWORD, IDENTIFIER, LITERAL, SPECIAL_SYMBOL, CONSTANT,
	
	// ERROR
	ERROR;
	
}
