package main.java.trees;

public enum TreeNodeType {

	// NON-TERMINALS
	CONDITIONAL, LOOP, REFERENCE, COMPOUND, CONDITION, CONDITION_BODY,
	
	// TERMINALS
	KEYWORD, IDENTIFIER, LITERAL;
	
}
